"""
Plasma USER.md writer.

Generates a human-readable markdown file describing the user, based on:
- Facts stored in the facts table
- Recent conversation patterns (future extension)

Design:
- USER.md has two regions:
    - An AUTO block (between <!-- plasma:auto-start --> / <!-- plasma:auto-end -->) — Plasma owns
    - Anything outside those markers — user owns, Plasma never touches
- Plasma regenerates the AUTO block from the facts table on each write
- Facts are rewritten to second person in a single left-to-right pass
  to avoid cascades like "You would like you to call you".
"""
from __future__ import annotations
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Iterable

from backend.modules.memory.store import MemoryStore

log = logging.getLogger("plasma.user_md")

PROJECT_ROOT = Path(__file__).resolve().parents[3]
USER_MD_PATH = PROJECT_ROOT / ".plasma" / "USER.md"

AUTO_START = "<!-- plasma:auto-start -->"
AUTO_END = "<!-- plasma:auto-end -->"


# One-pass rewriter rules. Order matters: multi-word forms come before "I".
# Each pattern uses a word-boundary; we tokenize by splitting on the first
# match and re-scan the REST only. This prevents "you" from being re-rewritten.
_REWRITE_RULES: list[tuple[str, str]] = [
    (r"\bI am\b",          "you are"),
    (r"\bI'm\b",           "you're"),
    (r"\bI have\b",        "you have"),
    (r"\bI've\b",          "you've"),
    (r"\bI had\b",         "you had"),
    (r"\bI was\b",         "you were"),
    (r"\bI will\b",        "you will"),
    (r"\bI'll\b",          "you'll"),
    (r"\bI would\b",       "you would"),
    (r"\bI'd\b",           "you'd"),
    (r"\bI do\b",          "you do"),
    (r"\bI don't\b",       "you don't"),
    (r"\bI can\b",         "you can"),
    (r"\bI can't\b",       "you can't"),
    (r"\bI like\b",        "you like"),
    (r"\bI love\b",        "you love"),
    (r"\bI hate\b",        "you hate"),
    (r"\bI want\b",        "you want"),
    (r"\bI need\b",        "you need"),
    (r"\bI live\b",        "you live"),
    (r"\bI work\b",        "you work"),
    (r"\bI prefer\b",      "you prefer"),
    (r"\bI\b",             "you"),
    (r"\bmyself\b",        "yourself"),
    (r"\bmine\b",          "yours"),
    (r"\bmy\b",            "your"),
    (r"\bme\b",            "you"),
]


def _rewrite_to_second_person(text: str) -> str:
    """Rewrite first-person pronouns to second person in a single left-to-right pass.

    Key insight: we tokenize, transform token by token. Once a token is written,
    it is NOT re-examined, so 'you' never gets rewritten again into 'you'.
    """
    # Build a single mega-regex; each match -> apply its specific replacement
    # by index. This keeps one pass only.
    pattern_map: list[tuple[re.Pattern, str]] = [
        (re.compile(p, re.IGNORECASE), repl) for p, repl in _REWRITE_RULES
    ]

    out: list[str] = []
    i = 0
    s = text
    while i < len(s):
        matched = False
        for pat, repl in pattern_map:
            m = pat.match(s, i)
            if m:
                # Preserve capitalization of the first letter if the original was capitalized
                original = m.group(0)
                new = repl
                if original and original[0].isupper():
                    new = new[0].upper() + new[1:] if new else new
                out.append(new)
                i = m.end()
                matched = True
                break
        if not matched:
            out.append(s[i])
            i += 1
    return "".join(out)


def _clean_fact(text: str) -> str:
    """Strip punctuation, normalize whitespace, rewrite to second person."""
    t = text.strip().rstrip(".?!").strip()
    t = re.sub(r"\s+", " ", t)
    t = _rewrite_to_second_person(t)
    return t


def _render_fact_section(title: str, facts: Iterable[dict]) -> str:
    # De-duplicate while preserving order (in case the DB has dupes)
    seen: set[str] = set()
    bullets: list[str] = []
    for f in facts:
        cleaned = _clean_fact(f["content"])
        key = cleaned.lower()
        if key in seen:
            continue
        seen.add(key)
        bullets.append(f"- {cleaned}")
    if not bullets:
        return ""
    return f"\n### {title}\n" + "\n".join(bullets) + "\n"


def build_auto_block(memory: MemoryStore) -> str:
    categories = {
        "identity":    "Identity",
        "preference":  "Preferences",
        "project":     "Projects",
        "user_note":   "Notes",
        "person":      "People",
        "place":       "Places",
    }

    lines: list[str] = []
    lines.append(f"_Auto-generated by Plasma at {datetime.now().isoformat(timespec='minutes')}_")
    lines.append("")
    lines.append(
        "_Edit anywhere OUTSIDE the auto-start / auto-end markers - those edits are preserved._"
    )
    lines.append("")

    has_any = False
    for cat_key, cat_title in categories.items():
        facts = memory.get_facts(category=cat_key, limit=50)
        section = _render_fact_section(cat_title, facts)
        if section:
            has_any = True
            lines.append(section)

    known = set(categories.keys())
    all_facts = memory.get_facts(limit=500)
    other = [f for f in all_facts if f.get("category") not in known]
    if other:
        has_any = True
        lines.append(_render_fact_section("Other", other))

    if not has_any:
        lines.append("_No facts stored yet. Use the `remember_this` skill to add some._")

    return "\n".join(lines).rstrip() + "\n"


def _wrap_auto_block(body: str) -> str:
    return f"{AUTO_START}\n{body}\n{AUTO_END}"


def _default_user_md(auto_block: str) -> str:
    return (
        "# USER.md\n\n"
        "_This file describes you. Plasma reads it before every reply so it knows your context._\n"
        "_Manual sections above/below the markers are kept. The block between markers is rebuilt automatically._\n\n"
        f"{_wrap_auto_block(auto_block)}\n"
    )


def write_user_md(memory: MemoryStore | None = None) -> Path:
    memory = memory or MemoryStore()
    auto_body = build_auto_block(memory)

    USER_MD_PATH.parent.mkdir(parents=True, exist_ok=True)

    if not USER_MD_PATH.exists():
        USER_MD_PATH.write_text(_default_user_md(auto_body), encoding="utf-8")
        log.info(f"USER.md created: {USER_MD_PATH}")
        return USER_MD_PATH

    current = USER_MD_PATH.read_text(encoding="utf-8")

    if AUTO_START in current and AUTO_END in current:
        pattern = re.compile(
            re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END),
            flags=re.DOTALL,
        )
        new_content = pattern.sub(_wrap_auto_block(auto_body), current)
    else:
        new_content = current.rstrip() + "\n\n" + _wrap_auto_block(auto_body) + "\n"

    USER_MD_PATH.write_text(new_content, encoding="utf-8")
    log.info(f"USER.md updated: {USER_MD_PATH}")
    return USER_MD_PATH


def read_user_md() -> str:
    if not USER_MD_PATH.exists():
        return ""
    return USER_MD_PATH.read_text(encoding="utf-8")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    path = write_user_md()
    print(f"Wrote: {path}")
    print("--- contents ---")
    print(read_user_md())