"""
Plasma skill templates — skeletons that the suggester stamps into real skills.

A template defines:
- A pattern (keywords that signal it's a fit for new utterances)
- A render() function that produces the final Python code for the skill file

When the suggester decides to propose a skill, it picks the best matching
template, fills in the user's actual trigger phrases, and offers it for approval.

These templates are intentionally simple. Real generation uses the user's own
data when possible (e.g., calculator works fully offline; weather hits an API).
"""
from __future__ import annotations
import re
from dataclasses import dataclass
from typing import Callable


@dataclass
class Template:
    name: str
    description: str
    keywords: list[str]
    default_triggers: list[str]
    render: Callable[[list[str]], str]


# --------------------------------------------------------------------------
# Template: weather (free Open-Meteo API, no key required)
# --------------------------------------------------------------------------
def _render_weather(triggers: list[str]) -> str:
    triggers_repr = repr(triggers)
    return f'''"""Skill: weather — current weather (Open-Meteo API, no key needed).

Auto-generated by Plasma's skill suggester.
"""
from __future__ import annotations
import re
import urllib.parse
import urllib.request
import json


META = {{
    "name": "weather",
    "description": "Returns current weather for a city.",
    "triggers": {triggers_repr},
    "example_utterances": ["What's the weather in Moers?", "Weather in Paris?"],
}}


def _geocode(city: str):
    url = f"https://geocoding-api.open-meteo.com/v1/search?name={{urllib.parse.quote(city)}}&count=1"
    with urllib.request.urlopen(url, timeout=5) as r:
        data = json.loads(r.read())
    results = data.get("results") or []
    if not results:
        return None
    return results[0]["latitude"], results[0]["longitude"], results[0]["name"]


def _fetch(lat, lon):
    url = (
        f"https://api.open-meteo.com/v1/forecast?latitude={{lat}}&longitude={{lon}}"
        f"&current=temperature_2m,weather_code,wind_speed_10m"
    )
    with urllib.request.urlopen(url, timeout=5) as r:
        return json.loads(r.read())


_WMO = {{
    0: "clear", 1: "mostly clear", 2: "partly cloudy", 3: "overcast",
    45: "foggy", 48: "foggy",
    51: "drizzle", 53: "drizzle", 55: "drizzle",
    61: "raining", 63: "raining", 65: "heavy rain",
    71: "snowing", 73: "snowing", 75: "heavy snow",
    80: "showers", 81: "showers", 82: "heavy showers",
    95: "thunderstorm",
}}


def run(args=None):
    utterance = ((args or {{}}).get("utterance") or "").strip()
    m = re.search(r"weather(?:\\s+(?:in|for|at))?\\s+([a-zA-Z][a-zA-Z\\s\\-]*?)\\s*[.?!]?$", utterance, re.IGNORECASE)
    city = m.group(1).strip() if m else "Moers"

    try:
        loc = _geocode(city)
        if not loc:
            return f"I couldn't find {{city}}."
        lat, lon, name = loc
        data = _fetch(lat, lon)
        cur = data.get("current", {{}})
        temp = cur.get("temperature_2m")
        code = cur.get("weather_code", 0)
        wind = cur.get("wind_speed_10m")
        desc = _WMO.get(code, "unknown conditions")
        return f"It's {{temp}} degrees and {{desc}} in {{name}}, with wind at {{wind}} km/h."
    except Exception as e:
        return f"I couldn't reach the weather service: {{e}}"


def self_test():
    return True
'''


# --------------------------------------------------------------------------
# Template: calculator (evaluates math safely)
# --------------------------------------------------------------------------
def _render_calculator(triggers: list[str]) -> str:
    triggers_repr = repr(triggers)
    return f'''"""Skill: calculator — evaluates simple arithmetic expressions safely.

Auto-generated by Plasma's skill suggester.
Safe-eval: only digits, operators, parens, decimal point allowed.
"""
from __future__ import annotations
import re


META = {{
    "name": "calculator",
    "description": "Computes basic arithmetic.",
    "triggers": {triggers_repr},
    "example_utterances": [
        "What is 12 times 7?",
        "Calculate 50 divided by 4",
        "Compute 17 plus 23",
    ],
}}


_WORD_TO_OP = {{
    "plus": "+", "added to": "+", "and": "+",
    "minus": "-", "subtract": "-",
    "times": "*", "multiplied by": "*",
    "divided by": "/", "over": "/",
}}


def _normalize(text: str) -> str:
    t = text.lower()
    for word, op in _WORD_TO_OP.items():
        t = t.replace(word, op)
    return t


def run(args=None):
    utterance = ((args or {{}}).get("utterance") or "").strip()
    expr = _normalize(utterance)
    expr = re.sub(r"[^0-9+\\-*/().\\s]", "", expr).strip()
    if not expr or not re.search(r"[0-9]", expr):
        return "I didn't catch a math expression."
    try:
        result = eval(expr, {{"__builtins__": {{}}}}, {{}})
    except Exception:
        return f"I couldn't compute that: {{expr}}"
    return f"{{expr}} equals {{result}}."


def self_test():
    return True
'''


# --------------------------------------------------------------------------
# Template: joke (curated list, no LLM needed)
# --------------------------------------------------------------------------
def _render_joke(triggers: list[str]) -> str:
    triggers_repr = repr(triggers)
    return f'''"""Skill: joke — returns a random short joke."""
from __future__ import annotations
import random


META = {{
    "name": "joke",
    "description": "Tells a short joke.",
    "triggers": {triggers_repr},
    "example_utterances": ["Tell me a joke", "Make me laugh"],
}}


_JOKES = [
    "Why do programmers prefer dark mode? Because light attracts bugs.",
    "I would tell you a UDP joke, but you might not get it.",
    "Why did the developer go broke? Because he used up all his cache.",
    "There are 10 kinds of people in the world: those who understand binary and those who don't.",
    "I'm reading a book on anti-gravity. It's impossible to put down.",
]


def run(args=None):
    return random.choice(_JOKES)


def self_test():
    return run() in _JOKES
'''


# --------------------------------------------------------------------------
# Template: timer (simple delayed acknowledgment, no real timer here)
# --------------------------------------------------------------------------
def _render_timer(triggers: list[str]) -> str:
    triggers_repr = repr(triggers)
    return f'''"""Skill: timer — acknowledges a duration request (placeholder)."""
from __future__ import annotations
import re


META = {{
    "name": "timer",
    "description": "Acknowledges a timer request.",
    "triggers": {triggers_repr},
    "example_utterances": ["Set a timer for 5 minutes"],
}}


def run(args=None):
    utterance = ((args or {{}}).get("utterance") or "").strip()
    m = re.search(r"(\\d+)\\s*(second|minute|hour)", utterance, re.IGNORECASE)
    if not m:
        return "How long should the timer run?"
    qty, unit = m.group(1), m.group(2).lower()
    return f"Timer noted for {{qty}} {{unit}}{{'s' if int(qty) != 1 else ''}}."


def self_test():
    return True
'''


# --------------------------------------------------------------------------
# Registry of available templates
# --------------------------------------------------------------------------
TEMPLATES: list[Template] = [
    Template(
        name="weather",
        description="Current weather lookup for any city.",
        keywords=["weather", "temperature", "forecast", "rain", "sunny"],
        default_triggers=["weather", "what's the weather", "weather in"],
        render=_render_weather,
    ),
    Template(
        name="calculator",
        description="Basic arithmetic.",
        keywords=["plus", "minus", "times", "divided", "calculate", "compute", "what is"],
        default_triggers=["calculate ", "compute ", "what is ", "how much is "],
        render=_render_calculator,
    ),
    Template(
        name="joke",
        description="Tells a joke.",
        keywords=["joke", "funny", "make me laugh"],
        default_triggers=["tell me a joke", "make me laugh", "tell a joke"],
        render=_render_joke,
    ),
    Template(
        name="timer",
        description="Sets a timer (acknowledgment only).",
        keywords=["timer", "minutes", "seconds", "alarm"],
        default_triggers=["set a timer", "timer for", "remind me in"],
        render=_render_timer,
    ),
]


def find_template_for(text: str) -> Template | None:
    """Return the best-matching template by keyword overlap, or None."""
    lower = text.lower()
    best: Template | None = None
    best_score = 0
    for tpl in TEMPLATES:
        score = sum(1 for kw in tpl.keywords if kw in lower)
        if score > best_score:
            best = tpl
            best_score = score
    return best if best_score > 0 else None