"""Skill: weather — current weather (Open-Meteo API, no key needed).

Auto-generated by Plasma's skill suggester.
"""
from __future__ import annotations
import re
import json
import httpx


META = {
    "name": "weather",
    "description": "Returns current weather for a city.",
    "triggers": ['weather', "what's the weather", 'weather in'],
    "example_utterances": ["What's the weather in Moers?", "Weather in Paris?"],
}


def _geocode(city: str):
    url = "https://geocoding-api.open-meteo.com/v1/search"
    data = httpx.get(url, params={"name": city, "count": 1}, timeout=5).raise_for_status().json()
    results = data.get("results") or []
    if not results:
        return None
    return results[0]["latitude"], results[0]["longitude"], results[0]["name"]


def _fetch(lat, lon):
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": lat, "longitude": lon,
        "current": "temperature_2m,weather_code,wind_speed_10m",
    }
    return httpx.get(url, params=params, timeout=5).raise_for_status().json()


_WMO = {
    0: "clear", 1: "mostly clear", 2: "partly cloudy", 3: "overcast",
    45: "foggy", 48: "foggy",
    51: "drizzle", 53: "drizzle", 55: "drizzle",
    61: "raining", 63: "raining", 65: "heavy rain",
    71: "snowing", 73: "snowing", 75: "heavy snow",
    80: "showers", 81: "showers", 82: "heavy showers",
    95: "thunderstorm",
}


def run(args=None):
    utterance = ((args or {}).get("utterance") or "").strip()
    m = re.search(r"weather(?:\s+(?:in|for|at))?\s+([a-zA-Z][a-zA-Z\s\-]*?)\s*[.?!]?$", utterance, re.IGNORECASE)
    city = m.group(1).strip() if m else "Moers"

    try:
        loc = _geocode(city)
        if not loc:
            return f"I couldn't find {city}."
        lat, lon, name = loc
        data = _fetch(lat, lon)
        cur = data.get("current", {})
        temp = cur.get("temperature_2m")
        code = cur.get("weather_code", 0)
        wind = cur.get("wind_speed_10m")
        desc = _WMO.get(code, "unknown conditions")
        return f"It's {temp} degrees and {desc} in {name}, with wind at {wind} km/h."
    except Exception as e:
        return f"I couldn't reach the weather service: {e}"


def self_test():
    return True
