"""Skill: weather — current weather (Open-Meteo API, no key needed).

Auto-generated by Plasma's skill suggester.
"""
from __future__ import annotations
import re
from backend.core.http_client import get as http_get


META = {
    "name": "weather",
    "description": "Returns current weather for a city.",
    "triggers": [
        'weather',
        "what's the weather",
        'weather in',
        'what is the weather',
        'how is the weather',
        'weather today',
        'weather outside',
        'wie ist das wetter',
        'wie wird das wetter',
        'wetter heute',
        'wetter in',
    ],
    "example_utterances": ["What's the weather in Moers?", "Weather in Paris?"],
}


def _geocode(city: str):
    url = "https://geocoding-api.open-meteo.com/v1/search"
    data = http_get(url, params={"name": city, "count": 1}).raise_for_status().json()
    results = data.get("results") or []
    if not results:
        return None
    return results[0]["latitude"], results[0]["longitude"], results[0]["name"]


def _fetch(lat, lon):
    url = "https://api.open-meteo.com/v1/forecast"
    params = {
        "latitude": lat, "longitude": lon,
        "current": "temperature_2m,weather_code,wind_speed_10m",
    }
    return http_get(url, params=params).raise_for_status().json()


_WMO = {
    0: "clear", 1: "mostly clear", 2: "partly cloudy", 3: "overcast",
    45: "foggy", 48: "foggy",
    51: "drizzle", 53: "drizzle", 55: "drizzle",
    61: "raining", 63: "raining", 65: "heavy rain",
    71: "snowing", 73: "snowing", 75: "heavy snow",
    80: "showers", 81: "showers", 82: "heavy showers",
    95: "thunderstorm",
}


DEFAULT_CITY = "Moers"

# Words that can follow "weather" but are not place names. Without this,
# "what's the weather today?" geocoded the word "today" and cheerfully
# reported the weather for a village called Todaya.
_NOT_A_PLACE = {
    "today", "tomorrow", "tonight", "now", "currently", "outside", "here",
    "like", "report", "forecast", "please", "there", "right", "just",
    "heute", "morgen", "jetzt", "draußen", "hier", "bitte",
    # Prepositions/filler that survive a mid-sentence match such as
    # "weather like in Paris" — otherwise the city becomes "in Paris".
    "in", "for", "at", "im", "für", "is", "it", "its",
}


def _parse_city(utterance: str) -> str | None:
    """Pull the city out of a weather question. None → use DEFAULT_CITY.

    Deliberately tolerant: the input is speech-to-text, so it arrives with
    stray punctuation, repeated phrases and misheard country names.
    """
    m = re.search(r"(?:weather|wetter)\b(.*)$", utterance, re.IGNORECASE | re.DOTALL)
    if not m:
        return None
    tail = re.split(r"[.?!]", m.group(1))[0]
    # Drop a leading preposition: "in Athens" → "Athens".
    tail = re.sub(r"^\s*(?:in|for|at|für|im|in der)\b", " ", tail, flags=re.IGNORECASE)
    # Keep the first comma segment so "Athens, Greece" geocodes as "Athens".
    # The old pattern simply failed to match here and silently fell back to
    # the default city — answering confidently about the wrong place.
    tail = tail.split(",")[0]
    words = [w for w in tail.split() if w.strip(".,?!-").lower() not in _NOT_A_PLACE]
    city = " ".join(words).strip(" -")
    return city or None


def run(args=None):
    utterance = ((args or {}).get("utterance") or "").strip()
    city = _parse_city(utterance) or DEFAULT_CITY

    try:
        loc = _geocode(city)
        if not loc:
            return f"I couldn't find {city}."
        lat, lon, name = loc
        data = _fetch(lat, lon)
        cur = data.get("current", {})
        temp = cur.get("temperature_2m")
        code = cur.get("weather_code", 0)
        wind = cur.get("wind_speed_10m")
        desc = _WMO.get(code, "unknown conditions")
        return f"It's {temp} degrees and {desc} in {name}, with wind at {wind} km/h."
    except Exception as e:
        return f"I couldn't reach the weather service: {e}"


def self_test():
    """Parsing only — no network, so it stays fast and offline-safe."""
    cases = {
        # A time word is not a city; fall back to the default.
        "what's the weather today?": None,
        "how is the weather": None,
        "weather outside": None,
        "wie ist das wetter": None,
        # Real places, including the comma form that used to fail outright.
        "what's the weather in Athens, Greece?": "Athens",
        "In Athens, what's the weather in Athens, Deutschland?": "Athens",
        "weather in Paris": "Paris",
        "wetter in Berlin": "Berlin",
        "what's the weather in New York today": "New York",
    }
    return all(_parse_city(q) == want for q, want in cases.items())
